import { Lato } from "next/font/google";
import "./globals.scss";
import NavBar from "@/components/NavBar";

const lato = Lato({
	variable: "--font-lato",
	subsets: ["latin"],
	weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
	title: "Le Café du Château",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fr">
			<body className={`${lato.variable} ${lato.className} antialiased`}>
				<NavBar />
				{children}
			</body>
		</html>
	);
}
